# GoReleaser configuration for astat
version: 2

builds:
  - id: astat
    main: ./main.go
    binary: astat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/sunil-saini/astat/internal/version.Version={{.Version}}
      - -X github.com/sunil-saini/astat/internal/version.Commit={{.Commit}}
      - -X github.com/sunil-saini/astat/internal/version.Date={{.Date}}
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy
    - bash -c "go build -o ./astat_local . && mkdir -p completions && ./astat_local completion bash > completions/astat.bash && ./astat_local completion zsh > completions/astat.zsh && ./astat_local completion fish > completions/astat.fish && rm ./astat_local"

archives:
  - id: astat
    formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

brews:
  - name: astat
    repository:
      owner: sunil-saini
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: https://github.com/sunil-saini/astat
    description: "A Lightning fast local AWS Stats indexer"
    license: MIT
    directory: Formula
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "astat"
      bash_completion.install "completions/astat.bash" => "astat"
      zsh_completion.install "completions/astat.zsh" => "_astat"
      fish_completion.install "completions/astat.fish"
    post_install: |
      system "#{bin}/astat", "install"
    test: |
      system "#{bin}/astat", "version"
